# Configuration file for image captioning project

data:
  train_images_dir: ../data/images/train
  val_images_dir: ../data/images/val
  test_images_dir: ../data/images/test
  train_captions_file: ../data/captions/train_captions.json
  val_captions_file: ../data/captions/val_captions.json
  test_captions_file: ../data/captions/test_captions.json
  vocab_file: ../data/processed/vocab.pkl

training:
  batch_size: 64
  epochs: 20
  learning_rate: 0.001
  checkpoint_dir: ../models/checkpoints
  saved_model_dir: ../models/saved_models
